### PR TITLE
Dev - SELFHOSTDNS_MAP_LAST_USED_INTERNAL changes for readability

### PR DESCRIPTION
**Pull request by AlvinSchiller**
Changed SELFHOSTDNS_MAP_LAST_USED_INTERNAL seperator from ";" to space, without leading and trailing (readability for debug and domain.conf).
Set new entry after request was successfull

### CODE REVIEW

**Comment by AlvinSchiller** [comment]
@Marvo2011 
Updated Usage:

- create a new TXT record for a subdomainname with the needed prefix e.g. "_acme-challenge.example.com" (default) or "alias.example.com" (dns alias mode)
  - for wildcard subdomains add a second TXT record for the identical subdomainname
- edit the TXT record and note the ID in (...) behind the subdomainname
- export each subdomainname (including the prefix) and the corresponding record IDs in SELFHOSTDNS_MAP like "subdomainname:RID1:RID2"
  - at least one RID must be set, up to two are supported for wildcard subdomains
  - each entry must be seperated by a space
- export username and password in SELFHOSTDNS_USERNAME and SELFHOSTDNS_PASSWORD
  - Note: For username you have to use your account / customer number. You can find them in any invoice or on the right top of the selfhost dashboard.

```
export SELFHOSTDNS_USERNAME="myname"
export SELFHOSTDNS_PASSWORD="mypass"
export SELFHOSTDNS_MAP="_acme-challenge.example.com:12345:98765 alias.example.com:11111"

acme.sh --issue -d example.com --dns dns_selfhost
```

**Comment by AlvinSchiller** [comment]
@Marvo2011  any idea why the DNS check is failing? seems nothing wrong with the implementation. looks like the dns resolving of letsencrypt is sometimes not getting the right TXT entry.
I ran the actions on a new branch again and it is failing randomly on a different distro every run...

Edit: there was a bug in the test suite (acmetest) so TEST_DNS_SLEEP wasn't used, if not explicitly set.
https://github.com/acmesh-official/acmetest/issues/19
Should now pass.

**Comment by Marvo2011** [comment]
@AlvinSchiller thanks I try it. For me it sucks always at fedora, but no really problems at the log. At the moment I'm very busy sorry for the late response.

**Comment by AlvinSchiller** [comment]
@Marvo2011 
Hopefully the fix will fix that too ^^
Regarding the failure in MacOS: I had the same error in one of my runs. The map values in the secrets must be set in double quotation marks, like "values"

**Comment by Marvo2011** [comment]
@AlvinSchiller thanks, interesting I will try it tomorrow with double quotes.

Edit: fedora seams fixed

**Comment by AlvinSchiller** [comment]
@Marvo2011 Strange error on the MacOS run :/ 
can you try and run all tests again? Maybe something is stuck in the setup on only retrying failed?

**Comment by Marvo2011** [comment]
@AlvinSchiller very strange error. TXT Records are corectly set.

```
[Tue Sep  6 06:23:23 UTC 2022] Cert success.
[Tue Sep  6 06:23:23 UTC 2022] Your cert is in: /Users/runner/.acme.sh/***/***.cer
[Tue Sep  6 06:23:23 UTC 2022] Your cert key is in: /Users/runner/.acme.sh/***/***.key
[Tue Sep  6 06:23:23 UTC 2022] The intermediate CA cert is in: /Users/runner/.acme.sh/***/ca.cer
[Tue Sep  6 06:23:23 UTC 2022] And the full chain certs is there: /Users/runner/.acme.sh/***/fullchain.cer
[Tue Sep  6 06:23:24 UTC 2022] _on_issue_success
[Tue Sep  6 06:23:24 UTC 2022] '' does not contain 'dns'
Run Failed
```

What you have exactly set in ".." all Secrets also the export keys or only values?

**Comment by AlvinSchiller** [comment]
@Marvo2011  only the value (TokenValueX) like "_acme-challenge.example.de:111111:222222 acmetestXyzRandomName.example.de:99999"

**Comment by Marvo2011** [comment]
@AlvinSchiller many thanks, it is merged and pushed to master 🎉🎉🎉🎉

**Pull request merged**
